SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

USE `dbfichasocioeconomica`;

DROP TABLE IF EXISTS `provincias`;
CREATE TABLE IF NOT EXISTS `provincias` (
	`id`                    int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`codigo`                varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
	`descripcion`           varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
	`codigodeptamento`   varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
	`codigoprovincia`      varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
	`departamento_id`       int(10) UNSIGNED NOT NULL,

	`activo`      			tinyint(1) NOT NULL DEFAULT '1',
	`created_at`  			timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at`  			timestamp NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=196 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('1','0101','CHACHAPOYAS','01','01','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('2','0102','BAGUA','01','02','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('3','0103','BONGARA','01','03','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('4','0104','LUYA','01','04','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('5','0105','RODRIGUEZDEMENDOZA','01','05','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('6','0106','CONDORCANQUI','01','06','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('7','0107','UTCUBAMBA','01','07','1',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('8','0201','HUARAZ','02','01','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('9','0202','AIJA','02','02','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('10','0203','BOLOGNESI','02','03','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('11','0204','CARHUAZ','02','04','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('12','0205','CASMA','02','05','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('13','0206','CORONGO','02','06','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('14','0207','HUAYLAS','02','07','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('15','0208','HUARI','02','08','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('16','0209','MARISCALLUZURIAGA','02','09','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('17','0210','PALLASCA','02','10','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('18','0211','POMABAMBA','02','11','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('19','0212','RECUAY','02','12','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('20','0213','SANTA','02','13','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('21','0214','SIHUAS','02','14','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('22','0215','YUNGAY','02','15','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('23','0216','ANTONIORAIMONDI','02','16','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('24','0217','CARLOSFERMINFITZCARRALD','02','17','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('25','0218','ASUNCION','02','18','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('26','0219','HUARMEY','02','19','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('27','0220','OCROS','02','20','2',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('28','0301','ABANCAY','03','01','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('29','0302','AYMARAES','03','02','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('30','0303','ANDAHUAYLAS','03','03','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('31','0304','ANTABAMBA','03','04','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('32','0305','COTABAMBAS','03','05','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('33','0306','GRAU','03','06','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('34','0307','CHINCHEROS','03','07','3',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('35','0401','AREQUIPA','04','01','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('36','0402','CAYLLOMA','04','02','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('37','0403','CAMANA','04','03','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('38','0404','CARAVELI','04','04','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('39','0405','CASTILLA','04','05','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('40','0406','CONDESUYOS','04','06','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('41','0407','ISLAY','04','07','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('42','0408','LAUNION','04','08','4',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('43','0501','HUAMANGA','05','01','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('44','0502','CANGALLO','05','02','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('45','0503','HUANTA','05','03','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('46','0504','LAMAR','05','04','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('47','0505','LUCANAS','05','05','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('48','0506','PARINACOCHAS','05','06','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('49','0507','VICTORFAJARDO','05','07','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('50','0508','HUANCASANCOS','05','08','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('51','0509','VILCASHUAMAN','05','09','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('52','0510','PAUCARDELSARASARA','05','10','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('53','0511','SUCRE','05','11','5',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('54','0601','CAJAMARCA','06','01','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('55','0602','CAJABAMBA','06','02','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('56','0603','CELENDIN','06','03','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('57','0604','CONTUMAZA','06','04','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('58','0605','CUTERVO','06','05','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('59','0606','CHOTA','06','06','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('60','0607','HUALGAYOC','06','07','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('61','0608','JAEN','06','08','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('62','0609','SANTACRUZ','06','09','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('63','0610','SANMIGUEL','06','10','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('64','0611','SANIGNACIO','06','11','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('65','0612','SANMARCOS','06','12','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('66','0613','SANPABLO','06','13','6',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('67','0701','CUSCO','07','01','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('68','0702','ACOMAYO','07','02','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('69','0703','ANTA','07','03','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('70','0704','CALCA','07','04','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('71','0705','CANAS','07','05','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('72','0706','CANCHIS','07','06','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('73','0707','CHUMBIVILCAS','07','07','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('74','0708','ESPINAR','07','08','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('75','0709','LACONVENCION','07','09','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('76','0710','PARURO','07','10','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('77','0711','PAUCARTAMBO','07','11','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('78','0712','QUISPICANCHIS','07','12','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('79','0713','URUBAMBA','07','13','7',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('80','0801','HUANCAVELICA','08','01','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('81','0802','ACOBAMBA','08','02','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('82','0803','ANGARAES','08','03','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('83','0804','CASTROVIRREYNA','08','04','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('84','0805','TAYACAJA','08','05','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('85','0806','HUAYTARA','08','06','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('86','0807','CHURCAMPA','08','07','8',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('87','0901','HUANUCO','09','01','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('88','0902','AMBO','09','02','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('89','0903','DOSDEMAYO','09','03','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('90','0904','HUAMALIES','09','04','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('91','0905','MARANON','09','05','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('92','0906','LEONCIOPRADO','09','06','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('93','0907','PACHITEA','09','07','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('94','0908','PUERTOINCA','09','08','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('95','0909','HUACAYBAMBA','09','09','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('96','0910','LAURICOCHA','09','10','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('97','0911','YAROWILCA','09','11','9',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('98','1001','ICA','10','01','10',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('99','1002','CHINCHA','10','02','10',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('100','1003','NAZCA','10','03','10',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('101','1004','PISCO','10','04','10',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('102','1005','PALPA','10','05','10',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('103','1101','HUANCAYO','11','01','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('104','1102','CONCEPCION','11','02','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('105','1103','JAUJA','11','03','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('106','1104','JUNIN','11','04','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('107','1105','TARMA','11','05','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('108','1106','YAULI','11','06','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('109','1107','SATIPO','11','07','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('110','1108','CHANCHAMAYO','11','08','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('111','1109','CHUPACA','11','09','11',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('112','1201','TRUJILLO','12','01','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('113','1202','BOLIVAR','12','02','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('114','1203','SANCHEZCARRION','12','03','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('115','1204','OTUZCO','12','04','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('116','1205','PACASMAYO','12','05','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('117','1206','PATAZ','12','06','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('118','1207','SANTIAGODECHUCO','12','07','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('119','1208','ASCOPE','12','08','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('120','1209','CHEPEN','12','09','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('121','1210','JULCAN','12','10','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('122','1211','GRANCHIMU','12','11','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('123','1212','VIRU','12','12','12',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('124','1301','CHICLAYO','13','01','13',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('125','1302','FERRENAFE','13','02','13',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('126','1303','LAMBAYEQUE','13','03','13',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('127','1401','LIMA','14','01','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('128','1402','CAJATAMBO','14','02','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('129','1403','CANTA','14','03','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('130','1404','CANETE','14','04','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('131','1405','HUAURA','14','05','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('132','1406','HUAROCHIRI','14','06','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('133','1407','YAUYOS','14','07','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('134','1408','HUARAL','14','08','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('135','1409','BARRANCA','14','09','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('136','1410','OYON','14','10','14',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('137','1501','MAYNAS','15','01','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('138','1502','ALTOAMAZONAS','15','02','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('139','1503','LORETO','15','03','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('140','1504','REQUENA','15','04','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('141','1505','UCAYALI','15','05','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('142','1506','MARISCALRAMONCASTILLA','15','06','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('143','1507','DATEMDELMARAÑON','15','07','15',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('144','1601','TAMBOPATA','16','01','16',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('145','1602','MANU','16','02','16',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('146','1603','TAHUAMANU','16','03','16',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('147','1701','MARISCALNIETO','17','01','17',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('148','1702','GENERALSANCHEZCERRO','17','02','17',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('149','1703','ILO','17','03','17',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('150','1801','PASCO','18','01','18',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('151','1802','DANIELALCIDESCARRION','18','02','18',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('152','1803','OXAPAMPA','18','03','18',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('153','1901','PIURA','19','01','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('154','1902','AYABACA','19','02','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('155','1903','HUANCABAMBA','19','03','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('156','1904','MORROPON','19','04','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('157','1905','PAITA','19','05','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('158','1906','SULLANA','19','06','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('159','1907','TALARA','19','07','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('160','1908','SECHURA','19','08','19',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('161','2001','PUNO','20','01','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('162','2002','AZANGARO','20','02','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('163','2003','CARABAYA','20','03','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('164','2004','CHUCUITO','20','04','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('165','2005','HUANCANE','20','05','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('166','2006','LAMPA','20','06','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('167','2007','MELGAR','20','07','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('168','2008','SANDIA','20','08','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('169','2009','SANROMAN','20','09','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('170','2010','YUNGUYO','20','10','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('171','2011','SANANTONIODEPUTINA','20','11','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('172','2012','ELCOLLAO','20','12','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('173','2013','MOHO','20','13','20',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('174','2101','MOYOBAMBA','21','01','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('175','2102','HUALLAGA','21','02','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('176','2103','LAMAS','21','03','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('177','2104','MARISCALCACERES','21','04','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('178','2105','RIOJA','21','05','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('179','2106','SANMARTIN','21','06','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('180','2107','BELLAVISTA','21','07','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('181','2108','TOCACHE','21','08','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('182','2109','PICOTA','21','09','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('183','2110','ELDORADO','21','10','21',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('184','2201','TACNA','22','01','22',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('185','2202','TARATA','22','02','22',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('186','2203','JORGEBASADRE','22','03','22',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('187','2204','CANDARAVE','22','04','22',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('188','2301','TUMBES','23','01','23',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('189','2302','CONTRALMIRANTEVILLAR','23','02','23',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('190','2303','ZARUMILLA','23','03','23',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('191','2401','CALLAO','24','01','24',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('192','2501','CORONELPORTILLO','25','01','25',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('193','2502','PADREABAD','25','02','25',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('194','2503','ATALAYA','25','03','25',1);
INSERT INTO `provincias` (`id`,`codigo`, `descripcion`,`codigodeptamento`,`codigoprovincia`,`departamento_id`, `activo`) VALUES  ('195','2504','PURUS','25','04','25',1);


COMMIT;
